# Generated by Django 5.2.12 on 2026-03-17 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('address', models.CharField(max_length=500, verbose_name='адрес')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('capacity', models.PositiveIntegerField(verbose_name='вместимость')),
            ],
            options={
                'verbose_name': 'Парковка',
                'verbose_name_plural': 'Парковки',
            },
        ),
        migrations.CreateModel(
            name='CarClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('vehicle_plate', models.CharField(max_length=20, unique=True, verbose_name='государственный регистрационный номер')),
                ('parkings', models.ManyToManyField(blank=True, related_name='allowed_cars', to='parking.parking', verbose_name='парковки')),
            ],
            options={
                'verbose_name': 'Автомобиль клиента',
                'verbose_name_plural': 'Автомобили клиентов',
            },
        ),
        migrations.CreateModel(
            name='ParkingControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='марка')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='модель')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='время въезда')),
                ('exited_at', models.DateTimeField(blank=True, null=True, verbose_name='время выезда')),
                ('car_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='parking.carclient', verbose_name='автомобиль клиента')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='parking.parking', verbose_name='парковка')),
            ],
            options={
                'verbose_name': 'Контроль парковки',
                'verbose_name_plural': 'Контроль парковки',
            },
        ),
    ]
